/*
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMAclItem.java */

package java8.sun.jmx.snmp.IPAcl;

class JDMAclItem extends SimpleNode {
  protected com.sun.jmx.snmp.IPAcl.JDMAccess access= null;
  protected com.sun.jmx.snmp.IPAcl.JDMCommunities com= null;

  JDMAclItem(int id) {
    super(id);
  }

  JDMAclItem(Parser p, int id) {
    super(p, id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMAclItem(id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(Parser p, int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMAclItem(p, id);
  }

  public com.sun.jmx.snmp.IPAcl.JDMAccess getAccess() {
    return access;
  }

  public com.sun.jmx.snmp.IPAcl.JDMCommunities getCommunities() {
    return com;
  }
}
