/*
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMAccess.java */

package java8.com.sun.jmx.snmp.IPAcl;


import java8.sun.jmx.snmp.IPAcl.AclEntryImpl;
import java8.sun.jmx.snmp.IPAcl.Parser;
import java8.sun.jmx.snmp.IPAcl.ParserConstants;
import java8.sun.jmx.snmp.IPAcl.SimpleNode;

class JDMAccess extends SimpleNode {
  protected int access= -1;

  JDMAccess(int id) {
    super(id);
  }

  JDMAccess(Parser p, int id) {
    super(p, id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMAccess(id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(Parser p, int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMAccess(p, id);
  }

  protected void putPermission(AclEntryImpl entry) {
    if (access == ParserConstants.RO) {
       // We have a read-only access.
       //
       entry.addPermission(SnmpAcl.getREAD());
    }
    if (access == ParserConstants.RW) {
       // We have a read-write access.
       //
       entry.addPermission(SnmpAcl.getREAD());
       entry.addPermission(SnmpAcl.getWRITE());
    }
  }
}
