/*
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMCommunities.java */

package java8.com.sun.jmx.snmp.IPAcl;


import java8.sun.jmx.snmp.IPAcl.AclEntryImpl;
import java8.sun.jmx.snmp.IPAcl.JDMCommunity;
import java8.sun.jmx.snmp.IPAcl.Parser;
import java8.sun.jmx.snmp.IPAcl.SimpleNode;

class JDMCommunities extends SimpleNode {
  JDMCommunities(int id) {
    super(id);
  }

  JDMCommunities(Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMCommunities(id);
  }

  public static Node jjtCreate(Parser p, int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMCommunities(p, id);
  }

  public void buildCommunities(AclEntryImpl entry){
        for (int i =0 ; i < children.length ; i++)
          entry.addCommunity(((JDMCommunity)children[i]).getCommunity());
  }
}
