/*
 * Copyright (c) 2000, 2003, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

/* Generated By:JJTree: Do not edit this line. JDMHostInform.java */

package java8.sun.jmx.snmp.IPAcl;

class JDMHostInform extends SimpleNode {
    protected String name= "";

    JDMHostInform(int id) {
        super(id);
    }

    JDMHostInform(Parser p, int id) {
        super(p, id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
        return new com.sun.jmx.snmp.IPAcl.JDMHostInform(id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(Parser p, int id) {
        return new com.sun.jmx.snmp.IPAcl.JDMHostInform(p, id);
    }
}
