/*
 * Copyright (c) 2000, 2003, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

/* Generated By:JJTree: Do not edit this line. JDMInformItem.java */

package java8.sun.jmx.snmp.IPAcl;

class JDMInformItem extends SimpleNode {
    protected com.sun.jmx.snmp.IPAcl.JDMInformCommunity comm = null;
    JDMInformItem(int id) {
        super(id);
    }

    JDMInformItem(Parser p, int id) {
        super(p, id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
        return new com.sun.jmx.snmp.IPAcl.JDMInformItem(id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(Parser p, int id) {
        return new com.sun.jmx.snmp.IPAcl.JDMInformItem(p, id);
    }

    public com.sun.jmx.snmp.IPAcl.JDMInformCommunity getCommunity(){
        return comm;
    }
}
