/*
 * Copyright (c) 2000, 2003, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

/* Generated By:JJTree: Do not edit this line. JDMInformInterestedHost.java */

package java8.sun.jmx.snmp.IPAcl;

class JDMInformInterestedHost extends SimpleNode {
    JDMInformInterestedHost(int id) {
        super(id);
    }

    JDMInformInterestedHost(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        super(p, id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
        return new com.sun.jmx.snmp.IPAcl.JDMInformInterestedHost(id);
    }

    public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
        return new com.sun.jmx.snmp.IPAcl.JDMInformInterestedHost(p, id);
    }
}
