/*
 * Copyright (c) 1997, 2012, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMTrapBlock.java */

package java8.sun.jmx.snmp.IPAcl;

import java.net.InetAddress;
import java.util.Hashtable;
import java.util.Vector;

class JDMTrapBlock extends com.sun.jmx.snmp.IPAcl.SimpleNode {
  JDMTrapBlock(int id) {
    super(id);
  }

  JDMTrapBlock(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
    super(p, id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMTrapBlock(id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(com.sun.jmx.snmp.IPAcl.Parser p, int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMTrapBlock(p, id);
  }

  /**
   * Do no need to go through this part of the tree for
   * building AclEntry.
   */
   @Override
   public void buildAclEntries(com.sun.jmx.snmp.IPAcl.PrincipalImpl owner, com.sun.jmx.snmp.IPAcl.AclImpl acl) {}

  /**
   * Do no need to go through this part of the tree for
   * building InformEntry.
   */
   @Override
   public void buildInformEntries(Hashtable<InetAddress, Vector<String>> dest) {}
}
