/*
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */


/* Generated By:JJTree: Do not edit this line. JDMTrapInterestedHost.java */

package java8.sun.jmx.snmp.IPAcl;

class JDMTrapInterestedHost extends SimpleNode {
  JDMTrapInterestedHost(int id) {
    super(id);
  }

  JDMTrapInterestedHost(Parser p, int id) {
    super(p, id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMTrapInterestedHost(id);
  }

  public static com.sun.jmx.snmp.IPAcl.Node jjtCreate(Parser p, int id) {
      return new com.sun.jmx.snmp.IPAcl.JDMTrapInterestedHost(p, id);
  }
}
